Feature Gemeenschappelijke parkeerruimten
woonstadrotterdam/woningwaardering pull request #104
Opened 2024-09-23 11:38 UTC by tiddoloos

2024-09-23 12:21 UTC, benverhees commented on woningwaardering/vera/bvg/model_uitbreidingen/eenheden_ruimte.py
> +    """
Willen we hier nog een github issue bij VERA voor aanmaken?

2024-09-23 13:37 UTC, sTomerG requested changes
In de README moet nog iets komen over model-uitbreidingen :)

2024-09-23 13:37 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/gemeenschappelijke_parkeerruimten/gemeenschappelijke_parkeerruimten.py
> +                    criterium += f" (gedeeld met {ruimte.gedeeld_met_aantal_eenheden} {'eenheid' if ruimte.gedeeld_met_aantal_eenheden == 1 else 'eenheden'})"
```suggestion
                    criterium += f" (gedeeld met {ruimte.gedeeld_met_aantal_eenheden} eenheden)"
```
in de regel erboven filteren we al op `ruimte.gedeeld_met_aantal_eenheden >=2`

2024-09-23 13:37 UTC, sTomerG commented on woningwaardering/vera/referentiedata/ruimtedetailsoort.py
> +    auto&#39;s.
kloppen deze gekke tekens hier?

2024-09-23 13:37 UTC, sTomerG commented on woningwaardering/vera/referentiedata/ruimtedetailsoort.py
> +    meer dan twee wielen, zoals auto&#39;s.
kloppen deze gekke tekens hier?

2024-09-23 13:37 UTC, sTomerG commented on woningwaardering/vera/referentiedata/ruimtedetailsoort.py
> +    parkeerplaatsen voor auto&#39;s.
kloppen deze gekke tekens hier?

2024-09-23 13:37 UTC, sTomerG commented on woningwaardering/vera/referentiedata/ruimtesoort.py
> +    of privé zijn. De term &#34;parkeergelegenheid&#34; omvat alle vormen van
kloppen deze gekke tekens hier?

2024-09-23 13:42 UTC, sTomerG commented on woningwaardering/vera/bvg/model_uitbreidingen/eenheden_ruimte.py
> +    """
https://github.com/Aedes-datastandaarden/vera-referentiedata/issues/110#issuecomment-2349013228 <- of hieraan toevoegen

2024-09-24 06:13 UTC, sTomerG requested changes

2024-09-24 06:13 UTC, sTomerG commented on README.md
Uitbreidingen m.b.t. parkeervoorzieningen moet nog even toegelicht worden :)

2024-09-24 06:13 UTC, sTomerG commented on woningwaardering/vera/bvg/model_uitbreidingen/eenheden_ruimte.py
> +    """
Wellicht moet de beschrijving iets explicieter zijn dat dit alleen mag gebruikt worden voor parkeervoorzieningen en het niet werkt voor andere ruimten? In theorie zou iemand bij bijvoorbeeld 2 gelijke slaapkamers qua oppervlakte het `aantal` property kunnen gaan gebruiken

2024-09-24 06:13 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/gemeenschappelijke_parkeerruimten/gemeenschappelijke_parkeerruimten.py
> +                logger.warning(
```suggestion
                logger.info(
```
opzich is dit niet zo spannend denk ik?

2024-09-24 06:13 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/gemeenschappelijke_parkeerruimten/gemeenschappelijke_parkeerruimten.py
> +                )
is dit niet dubbel? ivm regel 149-151

2024-09-24 07:16 UTC, sTomerG commented on README.md
> +Als uitbreiding op de referentie data is de `Ruimtesoort.Parkeergelegenheid` toegevoegd. Daarnaast zijn er verschillende parkerruimten (`Ruimtedetailsoort`) toegevoegd. Deze uitbreidingen zijn overge
```suggestion
Als uitbreiding op de referentiedata is de `Ruimtesoort.Parkeergelegenheid` toegevoegd. Daarnaast zijn er verschillende parkerruimten (`Ruimtedetailsoort`) toegevoegd. Deze uitbreidingen zijn overgenomen vanuit de github issue https://github.com/Aedes-datastandaarden/vera-referentiedata/issues/110#issuecomment-2190641829.
```
Engelse ziekte!!! ;)

2024-09-24 07:18 UTC, sTomerG approved these changes

2024-09-24 08:03 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/gemeenschappelijke_parkeerruimten/gemeenschappelijke_parkeerruimten.py
> +                        f" (gedeeld met {ruimte.gedeeld_met_aantal_eenheden} eenheden)"
Ik zou hier "eenheden" weglaten, of er "adressen" van maken.

2024-09-24 08:06 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/utils.py
> +        (  # binnenkort wordt dit niet meer ondersteund
Wat wordt hiermee bedoeld?

2024-09-24 08:10 UTC, benverhees commented on woningwaardering/vera/bvg/generated.py
> +    Geeft aan hoeveel van deze ruimte er zijn. Dit attribuut is aangemaakt om de rubriek 'Gemeenschappelijke parkeerruimten' van de woningwaardering te kunnen berekenen en te voorkomen dat alle gedee
Dit komt nu niet overeen met de omschrijving in https://github.com/woonstadrotterdam/woningwaardering/pull/104/files#diff-2185a71526762ac9cc195d0d7af011f8665225f60b813256539e1bf4327111b5R53. Ik denk dat het script nog een keer gedraaid moet worden.

2024-09-24 08:24 UTC, tiddoloos commented on woningwaardering/vera/bvg/generated.py
> +    Geeft aan hoeveel van deze ruimte er zijn. Dit attribuut is aangemaakt om de rubriek 'Gemeenschappelijke parkeerruimten' van de woningwaardering te kunnen berekenen en te voorkomen dat alle gedee
opnieuw draaien levert niks op. als ik op deze link druk dan zie ik deze zin erbij: "Dit attribuut wordt uitsluitend gebruikt in het berekenen van de punten voor Gemeenschappelijke Parkeerruimten." moet je nog refreshen misschien?

2024-09-24 10:13 UTC, benverhees commented on woningwaardering/vera/bvg/generated.py
> +    Geeft aan hoeveel van deze ruimte er zijn. Dit attribuut is aangemaakt om de rubriek 'Gemeenschappelijke parkeerruimten' van de woningwaardering te kunnen berekenen en te voorkomen dat alle gedee
Ja, die tekst zie ik dus wel in de uitbreiding, maar niet hier in de generated code.

2024-09-24 10:14 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/gemeenschappelijke_parkeerruimten/gemeenschappelijke_parkeerruimten.py
> +                        f" (gedeeld met {ruimte.gedeeld_met_aantal_eenheden} eenheden)"
Ik denk namelijk dat eenheden niet zoveel zegt voor bewoners, en zij gaan de woningwaardering ook ontvangen.

2024-09-24 11:35 UTC, benverhees approved these changes

2024-09-24 11:36 UTC, merged