Update referentiedata
woonstadrotterdam/woningwaardering pull request #123
Opened 2024-10-08 13:34 UTC by benverhees

2024-10-09 07:56 UTC, sTomerG commented
@benverhees moet in de README de versie van de referentiedata al worden geüpdatet?

2024-10-09 08:10 UTC, benverhees commented
> @benverhees moet in de README de versie van de referentiedata al worden geüpdatet?

Ah ja, goeie! Ik moet de readme nog bijwerken!

2024-10-11 15:49 UTC, benverhees commented
@sTomerG ik heb de readme bijgewerkt en nog een paar aanpassingen aan het referentie genereer script gedaan.

2024-10-15 10:39 UTC, sTomerG requested changes

2024-10-15 10:39 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/utils.py
> +            Ruimtedetailsoort.gemeenschappelijk_dakterras.code,
```suggestion
```
nu staat dakterras er twee keer in

2024-10-15 12:07 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/utils.py
> +            Ruimtedetailsoort.gemeenschappelijk_dakterras.code,
Doorgevoerd!

2024-10-15 13:32 UTC, sTomerG approved these changes

2024-10-15 20:17 UTC, merged