Feature/tms 143 keuken
woonstadrotterdam/woningwaardering pull request #46
Opened 2024-05-28 13:39 UTC by tiddoloos

2024-05-29 10:59 UTC, sTomerG commented on docs/implementatietoelichting-beleidsboeken/2024/zelfstandige_woonruimten.md
> +vanwege de kwaliteit van de voorzieningen als bedoeld in paragraaf [4.6.2](#462-voorzieningen-die-extra-kwaliteitspunten-opleveren).
```suggestion
In geval aan deze eisen niet wordt voldaan, is er geen sprake van een keukeninstallatie in de zin van het woningwaarderingsstelsel en worden er dus geen punten voor keukeninstallatie gerekend, ongeacht de lengte van het aanrecht (zie hierna). Ook kom je dan niet toe aan extra punten vanwege de kwaliteit van de voorzieningen als bedoeld in paragraaf [4.6.2](#462-voorzieningen-die-extra-kwaliteitspunten-opleveren).
```

2024-05-29 10:59 UTC, sTomerG commented on docs/implementatietoelichting-beleidsboeken/2024/zelfstandige_woonruimten.md
> +mits daarnaast voldoende vervangende (andere) kastruimte aanwezig is.
```suggestion
Een ingebouwde (onroerende) koelkast, vaatwasser en/of oven beschouwen we als onderkast, mits daarnaast voldoende vervangende (andere) kastruimte aanwezig is.
```

2024-05-29 10:59 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/keuken/keuken_2024.py
> +                f"Kan geen punten geven voor stelselgroep {Woningwaarderingstelselgroep.keuken.naam}: Geen keuken, aanrecht of aanrecht lengte gevonden voor eenheid {eenheid.id}"
```suggestion
                f"Kan geen punten geven voor stelselgroep {Woningwaarderingstelselgroep.keuken.naam}: Geen keuken, aanrecht of aanrechtlengte gevonden voor eenheid {eenheid.id}"
```

2024-05-29 10:59 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/keuken/keuken_2024.py
> +        ]
Indien we deze loop beetje meer zouden uitsplitsen is het wellicht iets leesbaarder en kan er een duidelijkere errormessage worden gedisplayed ipv die generieke op regel 88. Niet essentieel maar enige mogelijke verbetering die ik zie. Voor de rest top!

2024-05-29 15:12 UTC, benverhees approved these changes

2024-05-29 15:20 UTC, benverhees requested changes

2024-05-29 15:20 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/keuken/keuken_2024.py
> +            and ruimte.detail_soort.code == Ruimtedetailsoort.keuken.code
Een aanrecht kan ook in een woonkamer of slaapkamer staan, dit wordt dan als een open keuken gezien. Dus ik denk dat we hier ook op `woonkamer_en_of_keuken`, `woonkamer`, `slaapkamer` en `woon_en_of_slaapkamer` moeten checken.

2024-05-30 05:48 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/keuken/keuken_2024.py
> +        ]
Klopt. Alleen bij de huidige warning 
```python
logger.warning(
    f"Kan geen punten geven voor stelselgroep {Woningwaarderingstelselgroep.keuken.naam}: Geen keuken, aanrecht of aanrechtlengte gevonden voor eenheid {eenheid.id}"
)
```
 moet de gebruiker zelf nog 'puzzelen': 
- mis ik een keuken?
- mis ik een aanrecht?
- mis ik een aanrechtlengte?

Of interpreteer ik de warning verkeerd?

2024-05-30 07:09 UTC, tiddoloos commented on woningwaardering/stelsels/zelfstandige_woonruimten/keuken/keuken_2024.py
> +        ]
haha ja dat snap ik

2024-05-30 07:14 UTC, tiddoloos commented on woningwaardering/stelsels/zelfstandige_woonruimten/keuken/keuken_2024.py
> +        ]
ik ga wel ff wat klussen en zal het dan voorleggen

2024-05-30 11:08 UTC, benverhees requested changes

2024-05-30 11:08 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/keuken/keuken_2024.py
> +            )
Misschien nog zoiets voor de leesbaarheid:

```suggestion
            and (
                ruimte.detail_soort.code
                in [
                    Ruimtedetailsoort.keuken.code,
                    Ruimtedetailsoort.woonkamer_en_of_keuken.code,
                    Ruimtedetailsoort.woonkamer.code,
                    Ruimtedetailsoort.woon_en_of_slaapkamer.code,
                    Ruimtedetailsoort.slaapkamer.code,
                ]
            )
```

2024-05-30 11:08 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/keuken/keuken_2024.py
> +            == Bouwkundigelementdetailsoort.aanrecht.code
Hier kan je nu wel die helper gebruiken
```suggestion
            if heeft_bouwkundig_element(ruimte, Bouwkundigelementdetailsoort.aanrecht)
```

2024-05-30 11:08 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/keuken/keuken_2024.py
> +                for aanrecht in ruimte.bouwkundige_elementen
Hier zitten alle bouwkundige elementen nog in, niet alleen de aanrechten. Daar moeten we hier dus alsnog op filteren.

2024-05-30 11:30 UTC, benverhees requested changes

2024-05-30 11:30 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/keuken/keuken_2024.py
> +            ruimte
Als we hier een Tuple returnen
```suggestion
            (ruimte, bouwkundig_element)
```

2024-05-30 11:30 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/keuken/keuken_2024.py
> +            ]
Hier zitten alle bouwkundige elementen nog in, niet alleen de aanrechten. Daar moeten we hier dus alsnog op filteren. Met de Tuple van ruimte en aanrecht waar de ruimten_met_aanrecht definieren, hoeven we er maar 1x doorheen en heb je nog steeds de relatie tussen ruimte en aanrecht die we nodig hebben voor de log messages.
```suggestion
        if ruimten_met_aanrecht:
            ruimten_met_aanrecht_lengte = [
                (ruimte, aanrecht)
                for (ruimte, aanrecht) in ruimten_met_aanrecht
                if aanrecht.lengte
            ]
```

2024-05-30 11:30 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/keuken/keuken_2024.py
> +                    )
Hier dan ook:
```suggestion
        for (ruimte, aanrecht) in ruimten_met_aanrecht_lengte:
            logger.debug(
                f"Ruimte {ruimte.id} is een {ruimte.detail_soort} met een {Bouwkundigelementdetailsoort.aanrecht.naam} van {aanrecht.lengte} {Meeteenheid.millimeter.value} en komt in aanmerking voor stelselgroep {Woningwaarderingstelselgroep.keuken.naam}"
            )
            if aanrecht.lengte:
                if aanrecht.lengte < 1000:
                    punten = 0.0
                elif aanrecht.lengte >= 2000:
                    punten = 7.0
                else:
                    punten = 4.0

                logger.info(
                    f"Ruimte {ruimte.naam} met aanrecht lengte {aanrecht.lengte} millimeter krijgt {punten} punten voor stelselgroep {Woningwaarderingstelselgroep.keuken.naam}"
                )

                woningwaardering_groep.woningwaarderingen.append(
                    WoningwaarderingResultatenWoningwaardering(
                        criterium=WoningwaarderingResultatenWoningwaarderingCriterium(
                            naam="Lengte aanrecht",
                            meeteenheid=Meeteenheid.millimeter.value,
                        ),
                        aantal=aanrecht.lengte,
                        punten=punten,
                    )
                )
```

2024-05-30 13:46 UTC, sTomerG approved these changes

2024-05-30 20:29 UTC, benverhees approved these changes

2024-05-31 07:31 UTC, merged