Update referentiedata en readme
woonstadrotterdam/woningwaardering pull request #70
Opened 2024-07-11 12:13 UTC by sTomerG

2024-07-11 21:14 UTC, benverhees requested changes

2024-07-11 21:14 UTC, benverhees commented on README.md
> -In de VERA VHE modellen bestaat een `oppervlakten` attribuut op `EenhedenEenheid`. Dit attribuut is nog niet beschikbaar in de door ons gebruikte VERA BVG modellen. Dit attribuut en de bijbehorende c
Deze is wel toegevoegd aan het vera model in patch 5, maar nog niet geupdated in onze codebase, dus "officieel" moet deze tekst er nog in blijven tot we het Vera model hebbenn geupdated en het attribuut en de class uit onze uitbreiding verwijderd hebben.

2024-07-12 10:45 UTC, tiddoloos approved these changes

2024-07-16 06:15 UTC, sTomerG commented on README.md
> -In de VERA VHE modellen bestaat een `oppervlakten` attribuut op `EenhedenEenheid`. Dit attribuut is nog niet beschikbaar in de door ons gebruikte VERA BVG modellen. Dit attribuut en de bijbehorende c
heb het teruggezet!

2024-07-16 09:03 UTC, benverhees approved these changes

2024-07-16 09:40 UTC, benverhees approved these changes

2024-07-16 09:56 UTC, merged