Feature/tms 191 logger guidelines implementeren
woonstadrotterdam/woningwaardering pull request #73
Opened 2024-07-15 13:32 UTC by tiddoloos

2024-07-15 13:52 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/keuken/keuken_jan_2024.py
> +            raise ValueError(
Waarom is het ontbreken van een keuken een `ValueError` en bijvoorbeeld het ontbreken van een bouwjaar een geraisde warning?

2024-07-15 14:02 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_jan_2024.py
> +                raise TypeError(f"ruimte {ruimte.id} heeft geen detailsoort")
in `keuken_jan_2024.py` wordt er een warning geraised bij het niet hebben van een detail_soort bij een ruimte

2024-07-15 14:05 UTC, sTomerG commented on README.md
> +| WARNING  | 30               | Een indicatie dat er iets onverwachts is gebeurd, of dat er in de nabije toekomst een probleem kan optreden (bijv. 'schijfruimte bijna vol'). De software werkt nog ste
```suggestion
| WARNING  | 30               | Een indicatie dat er iets onverwachts is gebeurd, of dat er in de nabije toekomst een probleem kan optreden (bijv. 'schijfruimte bijna vol'). De software werkt nog steeds zoals verwacht.                                                                                                | Een warning wordt gelogd wanneer er bijvoorbeeld iets mist in de input data van de eenheid die ervoor zorgt dat bepaalde code niet uitgevoerd kan worden. Hetgeen waarvoor gewaarschuwd wordt hoeft geen fout op te leveren, maar is wel belangrijk genoeg om de gebruiker te waarschuwen. Zie het kopje [warnings](#warnings) voor meer informatie over het geven van warnings en hoe hier mee omgegaan wordt.                                                                                                                                                                                                                                                              |
```

2024-07-15 14:07 UTC, sTomerG commented on docs/implementatietoelichting-beleidsboeken/2024/jan/zelfstandige_woonruimten.md
> +### 4.13.2 Woning gelegen in beschermd stads- en dorpsgezicht
```suggestion
### ~~4.13.2 Woning gelegen in beschermd stads- en dorpsgezicht~~
```

volgensmij was het goed zoals het was en ondersteunen wij dit niet?

2024-07-15 14:08 UTC, sTomerG commented on docs/implementatietoelichting-beleidsboeken/2024/jan/zelfstandige_woonruimten.md
> +Voor woningen, niet zijnde Rijksmonument, binnen beschermd stads- of dorpsgezicht geldt geen toeslag van 50 punten. Wel geldt een 15% hogere maximale huurprijs indien:
```suggestion
~~Voor woningen, niet zijnde Rijksmonument, binnen beschermd stads- of dorpsgezicht geldt geen toeslag van 50 punten. Wel geldt een 15% hogere maximale huurprijs indien:~~
```

volgensmij was het goed zoals het was en ondersteunen wij dit niet?

2024-07-15 14:11 UTC, tiddoloos commented on docs/implementatietoelichting-beleidsboeken/2024/jan/zelfstandige_woonruimten.md
> +Voor woningen, niet zijnde Rijksmonument, binnen beschermd stads- of dorpsgezicht geldt geen toeslag van 50 punten. Wel geldt een 15% hogere maximale huurprijs indien:
Ik heb hier niet bewust iets aan gedaan

2024-07-15 14:14 UTC, tiddoloos commented on docs/implementatietoelichting-beleidsboeken/2024/jan/zelfstandige_woonruimten.md
> +### 4.13.2 Woning gelegen in beschermd stads- en dorpsgezicht
ik weet niet waarom die dingen opeens weg zijn

2024-07-15 14:16 UTC, sTomerG commented on docs/implementatietoelichting-beleidsboeken/2024/jan/zelfstandige_woonruimten.md
> +### 4.13.2 Woning gelegen in beschermd stads- en dorpsgezicht
@benverhees weet jij dit?

2024-07-15 14:16 UTC, sTomerG commented on docs/implementatietoelichting-beleidsboeken/2024/jan/zelfstandige_woonruimten.md
> +Voor woningen, niet zijnde Rijksmonument, binnen beschermd stads- of dorpsgezicht geldt geen toeslag van 50 punten. Wel geldt een 15% hogere maximale huurprijs indien:
@benverhees weet jij dit?

2024-07-15 14:35 UTC, tiddoloos commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_jan_2024.py
> +                raise TypeError(f"ruimte {ruimte.id} heeft geen detailsoort")
value error is de bedoeling. dus staat nu goed. We hadden laatst afgesproken dat we geen warning zouden raisen in deze gevallen, maar wel een exception.

2024-07-15 14:36 UTC, tiddoloos commented on docs/implementatietoelichting-beleidsboeken/2024/jan/zelfstandige_woonruimten.md
> +### 4.13.2 Woning gelegen in beschermd stads- en dorpsgezicht
volgens mij moeten dit kringeletjes zijn idd

2024-07-16 06:03 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/beschermd_monument_bmz/beschermd_monument_bmz_jul_2024.py
> +                UserWarning,
Wat wordt er verwacht als een eenheid geen monument is? Want dan zou je geen warning willen, denk ik

2024-07-16 06:07 UTC, sTomerG commented on README.md
> +Mocht door de gebruiker logging worden uitgezet, dan zullen de UserWarnings altijd te zien zijn voor de gebruiker.
Bij het ontbreken van een bouwjaar en energieprestatie wordt in regel 207 van _woningwaardering/stelsels/zelfstandige_woonruimten/energieprestatie/energieprestatie_jan_2024.py_ een `ValueError` gegenereerd, hoe verhoudt zich dat tot dit stukje tekst?

2024-07-16 07:03 UTC, tiddoloos commented on woningwaardering/stelsels/zelfstandige_woonruimten/beschermd_monument_bmz/beschermd_monument_bmz_jul_2024.py
> +                UserWarning,
dit betekent dat de monumenten (list) None is, dus niet duidelijk meegegeven in het input model.

2024-07-16 07:10 UTC, tiddoloos commented on woningwaardering/stelsels/zelfstandige_woonruimten/beschermd_monument_bmz/beschermd_monument_bmz_jul_2024.py
> +                UserWarning,
maar je kan hier wel redeneren dat er een fall back is, net als in Ben's PR, dus je daarom geen warning wil. Als je warnings filter dus aanpast krijg je een warning maar geen error en volgens mij is dat wat we willen. dus dan kan je de code wel laten doorgaan maar krijg je in je logs wel de warning van missende data.

2024-07-16 07:24 UTC, tiddoloos commented on README.md
> +Mocht door de gebruiker logging worden uitgezet, dan zullen de UserWarnings altijd te zien zijn voor de gebruiker.
ja je hebt wel een punt. laten we het hier nog over hebben. Ik denk dat we de errors op input data wellicht helemaal kunnen vervangen met warnings.warn().

2024-07-16 07:41 UTC, tiddoloos commented on README.md
> +Mocht door de gebruiker logging worden uitgezet, dan zullen de UserWarnings altijd te zien zijn voor de gebruiker.
we meoten deze afweging maken:
- wat staan we nooit toe? -> raise ...
- wat staan we toen bij warnings.simplefilter("default") (en dus niet bij warnings.simplefilter("error"))
- wat staan we altijd toe? -> geen warnings.warn of raise

2024-07-16 14:13 UTC, sTomerG requested changes

2024-07-16 14:13 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/utils.py
>                  f"De netto oppervlakte van {aantal_ruimte_kasten} verbonden {aantal_ruimte_kasten == 1 and 'kast' or 'kasten'} is opgeteld bij {ruimte.naam}"
```suggestion
                f"Ruimte {ruimte.naam} ({ruimte.id}): de netto oppervlakte van {aantal_ruimte_kasten} verbonden {'kast' if aantal_ruimte_kasten == 1 else 'kasten'} is erbij opgeteld."
```

2024-07-16 14:13 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_jan_2024.py
> +                warnings.warn(f"ruimte {ruimte.id} heeft geen detailsoort", UserWarning)
```suggestion
                warnings.warn(f"Ruimte {ruimte.naam} ({ruimte.id}) heeft geen detailsoort.", UserWarning)
```

2024-07-16 14:13 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_jan_2024.py
> +                        f"De overige ruimten hebben bij elkaar {totaal_punten_overige_ruimten} punten behaald: {ruimte.naam} ({ruimte.id}) wordt niet meegeteld voor Verwarming."
```suggestion
                        f"Ruimte {ruimte.naam} ({ruimte.id}): wordt niet meegeteld voor {Woningwaarderingstelselgroep.verwarming.naam}, omdat de overige ruimten bij elkaar {totaal_punten_overige_ruimten} punten hebben behaald."
```

2024-07-16 14:13 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_jan_2024.py
> +                        f"De maximum punten voor {Ruimtesoort.overige_ruimtes.naam} zijn behaald: punten voor {ruimte.naam} ({ruimte.id}) worden gecorrigeerd."
```suggestion
                        f"Ruimte {ruimte.naam} ({ruimte.id}): punten worden gecorrigeerd. De maximum punten voor {Ruimtesoort.overige_ruimtes.naam} zijn behaald."
```

2024-07-16 15:48 UTC, tiddoloos commented on woningwaardering/stelsels/zelfstandige_woonruimten/punten_voor_de_woz_waarde/punten_voor_de_woz_waarde_jan_2024.py
>              woz_waarde = 0
even aparte story ivm test output aanpassen voor woz

2024-07-23 11:35 UTC, sTomerG submitted a review, later dismissed

2024-07-23 14:52 UTC, sTomerG approved these changes

2024-07-23 20:18 UTC, benverhees requested changes

2024-07-23 20:18 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/keuken/keuken_jan_2024.py
> +        "/Users/tomergabay/Documents/woonstad_rotterdam/code_projects/woningwaardering/tests/data/zelfstandige_woonruimten/stelselgroepen/keuken/input/keuken_zonder_aanrecht.json",
@sTomerG deze moet relatief gemaakt worden

2024-07-24 07:34 UTC, sTomerG approved these changes

2024-07-24 09:57 UTC, benverhees approved these changes

2024-07-24 09:58 UTC, merged