Feature Energieprestatie
woonstadrotterdam/woningwaardering pull request #94
Opened 2024-09-03 14:28 UTC by tiddoloos

- energieprestatie implementatie voor beleidsboek 2024-07-01
- aanpassen `utils.energieprestatie_met_geldig_label` zodat logging duidelijker wordt

2024-09-03 15:15 UTC, sTomerG requested changes

2024-09-03 15:15 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/energieprestatie/energieprestatie.py
> +            ),  # Overgangsrecht kleine woningen ≤ 40 m2 veravlt
is dit hier nodig? dan moeten we sws nieuwe release op 1 januari 2025

2024-09-04 06:56 UTC, tiddoloos commented on woningwaardering/stelsels/zelfstandige_woonruimten/energieprestatie/energieprestatie.py
> +            ),  # Overgangsrecht kleine woningen ≤ 40 m2 veravlt
veranderd

2024-09-04 09:49 UTC, benverhees commented on tests/data/generiek/input/37101000032.json
> +  "monumenten": [],
Ik had hier `monumenten` weggelaten zodat we ook de code die de api van cultureelerfgoed raadpleegt testen.

2024-09-04 09:49 UTC, benverhees commented on tests/data/zelfstandige_woonruimten/input/20002000126.json
> +  "monumenten": [],
Ik had hier `monumenten` weggelaten zodat we ook de code die de api van cultureelerfgoed raadpleegt testen.

2024-09-04 09:55 UTC, benverhees commented on tests/data/zelfstandige_woonruimten/output/12006000004.json
> +    },
Dit pand heeft sinds 24-07-2024 wel een energieprestatie. Willen we die in de testdata bijwerken zodat het overeeenkomt met de werkelijkheid of laten we het zo?

2024-09-04 09:56 UTC, benverhees commented on tests/data/zelfstandige_woonruimten/output/20002000126.json
> +    },
Dit pand heeft sinds 24-07-2024 wel een energieprestatie. Willen we die in de testdata bijwerken zodat het overeeenkomt met de werkelijkheid of laten we het zo?

2024-09-04 10:05 UTC, benverhees commented on tests/data/zelfstandige_woonruimten/output/81065000089.json
> +      ]
Het lijkt erop dat hier iets misgaat met de woningwaardering. Hoort het aantal m2 en de meeteenheid er in te staan?

2024-09-04 10:08 UTC, benverhees commented on tests/data/zelfstandige_woonruimten/stelselgroepen/energieprestatie/output/epv_egw.json
> +            "naam": "EPV Eengezinswoning"
Willen we hier niet het label blijven weergeven zodat duidelijk is dat we tot die punten zijn gekomen?

2024-09-04 10:21 UTC, tiddoloos commented on tests/data/zelfstandige_woonruimten/output/81065000089.json
> +      ]
ah ja je hebt gelijk! Er wordt gekeken naar de gebruiksoppervlakte thermische zone om te bepalen of de eenheid binnne het overgangsrecht  valt, maar het is onnodig om die meeteenheid te noteren denk ik

2024-09-04 10:48 UTC, benverhees commented on woningwaardering/stelsels/utils.py
> +    ]
Je kan dit typed maken op deze manier, dan kan de `# type: ignore [no-untyped-call]` op regel 260 ook weg;
```suggestion
    vereiste_attributen: List[Tuple[str, Callable[[EenhedenEnergieprestatie], bool]]] = [
        ("registratiedatum", lambda ep: ep.registratiedatum is not None),
        ("soort", lambda ep: ep.soort is not None and ep.soort.code is not None),
        ("status", lambda ep: ep.status is not None and ep.status.code is not None),
        ("begindatum", lambda ep: ep.begindatum is not None),
        ("einddatum", lambda ep: ep.einddatum is not None),
        ("label", lambda ep: ep.label is not None and ep.label.code is not None),
    ]
```

2024-09-04 10:49 UTC, benverhees commented on woningwaardering/stelsels/utils.py
> +import warnings
```suggestion
from typing import Callable, List, Tuple
import warnings
```

2024-09-04 10:51 UTC, benverhees commented on woningwaardering/stelsels/utils.py
>  from decimal import ROUND_HALF_UP, Decimal
Deze import is nodig voor een typing fix verderop

```suggestion
from decimal import ROUND_HALF_UP, Decimal
from typing import Callable, List, Tuple
```

2024-09-04 13:25 UTC, benverhees commented on tests/data/zelfstandige_woonruimten/output/12006000004.json
> +    },
Dit pand heeft sinds 24-07-2024 wel een energieprestatie. Willen we die in de testdata bijwerken zodat het overeeenkomt met de werkelijkheid of laten we het zo?

2024-09-04 13:38 UTC, sTomerG approved these changes

2024-09-04 14:23 UTC, merged